import React from 'react'
import "./Sidebar.css"

export default function () {
  return (
    <aside className='sidebar'>
      <ul className='sidebar__list'>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
        <li className='sidebar__list__item'>Test</li>
      </ul>
    </aside>
  )
}
